<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.youdatax.dsp</groupId>
  <artifactId>youdatax-dsp-v2025-catalog-api-http</artifactId>
  <version>0.0.3.0</version>
  <name>yospace-dsp-catalog-http-api-2025</name>
  <description>yospace-dsp-catalog-http-api-2025</description>
  
  <dependencies> 
<!--    api(project(":data-protocols:dsp:dsp-spi"))-->
      <dependency>
        <groupId>com.yospace.dsp</groupId>
        <artifactId>yospace-dsp-core-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    api(project(":data-protocols:dsp:dsp-2025:dsp-spi-2025"))-->
      <dependency>
        <groupId>com.yospace.dsp</groupId>
        <artifactId>yospace-dsp-v2025-core-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":data-protocols:dsp:dsp-http-spi"))-->
      <dependency>
        <groupId>com.yospace.dsp</groupId>
        <artifactId>yospace-dsp-core-spi-http</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":spi:common:core-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":spi:common:web-spi"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>web-spi</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    api(project(":spi:common:json-ld-spi"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>json-ld-spi</artifactId>
        <version>0.18.0</version>
      </dependency>
<!--    api(project(":spi:control-plane:control-plane-spi"))-->
      <dependency>
        <groupId>com.yospace.controlplane</groupId>
        <artifactId>yospace-control-plane-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    implementation(project(":extensions:common:http:lib:jersey-providers-lib"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>jersey-providers-lib</artifactId>
        <version>0.15.1</version>
      </dependency>    
<!--    implementation(project(":data-protocols:dsp:dsp-lib:dsp-catalog-lib:dsp-catalog-validation-lib"))-->
      <dependency>
        <groupId>com.yospace.dsp</groupId>
        <artifactId>yospace-dsp-core-catalog-lib-validation</artifactId>  
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    implementation(project(":data-protocols:dsp:dsp-lib:dsp-catalog-lib:dsp-catalog-http-api-lib"))-->
      <dependency>
        <groupId>com.yospace.dsp</groupId>
        <artifactId>yospace-dsp-core-catalog-lib-http-api</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    implementation(libs.jakarta.rsApi)
jakarta-rsApi = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "rsApi" }-->
      <dependency>
        <groupId>jakarta.ws.rs</groupId>
        <artifactId>jakarta.ws.rs-api</artifactId>
        <version>4.0.0</version>
      </dependency>
      
<!--    testImplementation(testFixtures(project(":extensions:common:http:jersey-core")))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>jersey-core</artifactId>
        <version>0.18.0</version>
      </dependency>
<!--    testImplementation(project(":core:common:junit"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>junit</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    testImplementation(libs.restAssured)
restAssured = { module = "io.rest-assured:rest-assured", version.ref = "restAssured" }-->
      <dependency>
        <groupId>io.rest-assured</groupId>
        <artifactId>rest-assured</artifactId>
        <version>5.5.6</version>
      </dependency>    
<!--    testImplementation(testFixtures(project(":data-protocols:dsp:dsp-lib:dsp-catalog-lib:dsp-catalog-http-api-lib")))  
       <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>dsp-catalog-http-api-lib</artifactId>
        <version>0.15.1</version>
      </dependency>  --> 
    </dependencies>
</project>