<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.youdatax.dsp</groupId>
  <artifactId>youdatax-dsp-v2025-negotiation-api-http</artifactId>
  <version>0.0.3-SNAPSHOT</version>
  <name>yospace-dsp-negotiation-http-api-2025</name>
  <description>yospace-dsp-negotiation-http-api-2025</description>
  
  <dependencies>
<!--    api(project(":data-protocols:dsp:dsp-spi"))-->
      <dependency>
        <groupId>com.yospace.dsp</groupId>
        <artifactId>yospace-dsp-core-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>
<!--    api(project(":data-protocols:dsp:dsp-2025:dsp-spi-2025"))-->
      <dependency>
        <groupId>org.youdatax.dsp</groupId>
        <artifactId>youdatax-dsp-v2025-core-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":data-protocols:dsp:dsp-http-spi"))-->
      <dependency>
        <groupId>com.yospace.dsp</groupId>
        <artifactId>yospace-dsp-core-spi-http</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
 <!--   api(project(":spi:common:core-spi"))-->
      <dependency>
        <groupId>com.yospace.core</groupId>
        <artifactId>yospace-core-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":spi:common:web-spi"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>web-spi</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    api(project(":spi:control-plane:control-plane-spi"))-->
      <dependency>
        <groupId>com.yospace.controlplane</groupId>
        <artifactId>yospace-control-plane-spi</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    api(project(":extensions:common:json-ld"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>json-ld</artifactId>
        <version>0.15.1</version>
      </dependency>
<!--    implementation(project(":data-protocols:dsp:dsp-lib:dsp-negotiation-lib:dsp-negotiation-validation-lib"))-->
      <dependency>
        <groupId>com.yospace.dsp</groupId> 
        <artifactId>yospace-dsp-core-negotiation-lib-validation</artifactId>
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    implementation(project(":data-protocols:dsp:dsp-lib:dsp-negotiation-lib:dsp-negotiation-http-api-lib"))-->
      <dependency>
        <groupId>com.yospace.dsp</groupId>
        <artifactId>yospace-dsp-core-negotiation-lib-http-api</artifactId>  
        <version>0.0.3-SNAPSHOT</version>
      </dependency>    
<!--    implementation(project(":extensions:common:http:lib:jersey-providers-lib"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>jersey-providers-lib</artifactId>
        <version>0.18.0</version>
      </dependency>
<!--    implementation(libs.jakarta.rsApi)-->

      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>core-spi</artifactId>
        <version>0.18.0</version>
      </dependency>
<!--    testImplementation(project(":core:common:junit"))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>junit</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    testImplementation(testFixtures(project(":extensions:common:http:jersey-core")))-->
      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>jersey-core</artifactId>
        <version>0.18.0</version>
      </dependency>    
<!--    testImplementation(libs.restAssured)-->

      <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>core-spi</artifactId>
        <version>0.10.0</version>
      </dependency>    
<!--    testImplementation(testFixtures(project(":data-protocols:dsp:dsp-lib:dsp-negotiation-lib:dsp-negotiation-http-api-lib")))  -->
       <dependency>
        <groupId>org.eclipse.edc</groupId>
        <artifactId>dsp-negotiation-http-api-lib</artifactId>
        <version>0.18.0</version>
      </dependency>   
   </dependencies>   
</project>